// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Drug struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Power                int32    `protobuf:"varint,3,opt,name=power,proto3" json:"power,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Drug) Reset()         { *m = Drug{} }
func (m *Drug) String() string { return proto.CompactTextString(m) }
func (*Drug) ProtoMessage()    {}
func (*Drug) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *Drug) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Drug.Unmarshal(m, b)
}
func (m *Drug) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Drug.Marshal(b, m, deterministic)
}
func (m *Drug) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Drug.Merge(m, src)
}
func (m *Drug) XXX_Size() int {
	return xxx_messageInfo_Drug.Size(m)
}
func (m *Drug) XXX_DiscardUnknown() {
	xxx_messageInfo_Drug.DiscardUnknown(m)
}

var xxx_messageInfo_Drug proto.InternalMessageInfo

func (m *Drug) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Drug) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Drug) GetPower() int32 {
	if m != nil {
		return m.Power
	}
	return 0
}

// Created a blank get request
type GetRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

type Response struct {
	Created              bool     `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

type GetResponse struct {
	// Added a pluralised consignment to our generic response message
	Drug                 []*Drug  `protobuf:"bytes,2,rep,name=drug,proto3" json:"drug,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetDrug() []*Drug {
	if m != nil {
		return m.Drug
	}
	return nil
}

func init() {
	proto.RegisterType((*Drug)(nil), "proto.Drug")
	proto.RegisterType((*GetRequest)(nil), "proto.GetRequest")
	proto.RegisterType((*Response)(nil), "proto.Response")
	proto.RegisterType((*GetResponse)(nil), "proto.GetResponse")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 218 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0xcd, 0x4e, 0x85, 0x30,
	0x10, 0x85, 0xa5, 0x17, 0xbc, 0xd7, 0xa9, 0x3f, 0x71, 0xe2, 0xa2, 0xb9, 0x1b, 0x49, 0xe3, 0x82,
	0x85, 0x61, 0x81, 0x2f, 0x60, 0xa2, 0x09, 0xfb, 0xfa, 0x04, 0x08, 0x13, 0xc2, 0x42, 0x8a, 0x6d,
	0xd1, 0xd7, 0x37, 0x4c, 0x21, 0xb2, 0x6a, 0xcf, 0x99, 0x33, 0x27, 0xdf, 0xc0, 0x8d, 0x27, 0xf7,
	0x33, 0xb4, 0x54, 0x4e, 0xce, 0x06, 0x8b, 0x19, 0x3f, 0xfa, 0x15, 0xd2, 0x77, 0x37, 0xf7, 0x78,
	0x0b, 0x62, 0xe8, 0x54, 0x92, 0x27, 0xc5, 0x95, 0x11, 0x43, 0x87, 0x08, 0xe9, 0xd8, 0x7c, 0x91,
	0x12, 0xec, 0xf0, 0x1f, 0x1f, 0x20, 0x9b, 0xec, 0x2f, 0x39, 0x75, 0xc8, 0x93, 0x22, 0x33, 0x51,
	0xe8, 0x6b, 0x80, 0x9a, 0x82, 0xa1, 0xef, 0x99, 0x7c, 0xd0, 0x4f, 0x70, 0x32, 0xe4, 0x27, 0x3b,
	0x7a, 0x42, 0x05, 0xc7, 0xd6, 0x51, 0x13, 0x28, 0x16, 0x9f, 0xcc, 0x26, 0x75, 0x09, 0x92, 0x77,
	0xd6, 0xe0, 0x23, 0xa4, 0x9d, 0x9b, 0x7b, 0x25, 0xf2, 0x43, 0x21, 0x2b, 0x19, 0x09, 0xcb, 0x85,
	0xcb, 0xf0, 0xa0, 0xb2, 0x20, 0x17, 0xf5, 0x11, 0x2f, 0xc0, 0x67, 0x80, 0x37, 0x6e, 0x62, 0xf4,
	0x7d, 0xfe, 0x7c, 0xb7, 0x8a, 0xad, 0x5b, 0x5f, 0x60, 0x05, 0xc7, 0x9a, 0x02, 0x47, 0xef, 0xd7,
	0xe9, 0x3f, 0xf0, 0x19, 0xf7, 0xd6, 0xb6, 0xf3, 0x79, 0xc9, 0xe6, 0xcb, 0x5f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x29, 0x3c, 0xed, 0x98, 0x35, 0x01, 0x00, 0x00,
}
