// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: service.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for DrugService service

type DrugService interface {
	CreateDrug(ctx context.Context, in *Drug, opts ...client.CallOption) (*Response, error)
	// Created a new method
	GetDrug(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*GetResponse, error)
}

type drugService struct {
	c    client.Client
	name string
}

func NewDrugService(name string, c client.Client) DrugService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "proto"
	}
	return &drugService{
		c:    c,
		name: name,
	}
}

func (c *drugService) CreateDrug(ctx context.Context, in *Drug, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "DrugService.CreateDrug", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drugService) GetDrug(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*GetResponse, error) {
	req := c.c.NewRequest(c.name, "DrugService.GetDrug", in)
	out := new(GetResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DrugService service

type DrugServiceHandler interface {
	CreateDrug(context.Context, *Drug, *Response) error
	// Created a new method
	GetDrug(context.Context, *GetRequest, *GetResponse) error
}

func RegisterDrugServiceHandler(s server.Server, hdlr DrugServiceHandler, opts ...server.HandlerOption) error {
	type drugService interface {
		CreateDrug(ctx context.Context, in *Drug, out *Response) error
		GetDrug(ctx context.Context, in *GetRequest, out *GetResponse) error
	}
	type DrugService struct {
		drugService
	}
	h := &drugServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&DrugService{h}, opts...))
}

type drugServiceHandler struct {
	DrugServiceHandler
}

func (h *drugServiceHandler) CreateDrug(ctx context.Context, in *Drug, out *Response) error {
	return h.DrugServiceHandler.CreateDrug(ctx, in, out)
}

func (h *drugServiceHandler) GetDrug(ctx context.Context, in *GetRequest, out *GetResponse) error {
	return h.DrugServiceHandler.GetDrug(ctx, in, out)
}
